###
GET http://localhost:5000/api/product HTTP/1.1


###

POST http://localhost:5000/api/user/login HTTP/1.1
content-type: application/json

{
    "email": "saheb.test@gmail.com",
    "password": "12345689"
}

###

POST http://localhost:5000/api/user/register HTTP/1.1
content-type: application/json

{
    "email": "manirmp1386",
    "password": "12345689",
    "name":"wahed m",
    "phoneNumber":"312413141"
}
